# Generated by Django 6.0.3 on 2026-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Author',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publishing_name', models.CharField(max_length=50)),
                ('real_name', models.CharField(blank=True, max_length=50)),
                ('author_slug', models.SlugField(blank=True, unique=True)),
                ('photo', models.ImageField(blank=True, null=True, upload_to='authors/')),
            ],
        ),
    ]
