# Generated by Django 6.0.3 on 2026-04-02 13:32

import Reading_Club.book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='photo',
            field=models.ImageField(blank=True, null=True, upload_to='authors/', validators=[Reading_Club.book.validators.validate_file_size]),
        ),
    ]
