# Generated by Django 6.0.3 on 2026-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('author', '0002_alter_author_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='author',
            name='publishing_name',
            field=models.CharField(max_length=50, unique=True),
        ),
    ]
