# Generated by Django 6.0.3 on 2026-04-02 12:48

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
        ('auth', '0012_alter_user_first_name_max_length'),
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='read_list',
            field=models.ManyToManyField(blank=True, related_name='users_books_list', to='book.book'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='user_permissions',
            field=models.ManyToManyField(blank=True, help_text='Specific permissions for this user.', related_name='user_set', related_query_name='user', to='auth.permission', verbose_name='user permissions'),
        ),
        migrations.AddField(
            model_name='baseuser',
            name='wishlist',
            field=models.ManyToManyField(blank=True, related_name='users_wishlist', to='book.book'),
        ),
    ]
