# Generated by Django 6.0.3 on 2026-04-14 12:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='baseuser',
            name='nickname',
            field=models.CharField(max_length=30),
        ),
    ]
