# Generated by Django 6.0.3 on 2026-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_baseuser_nickname'),
    ]

    operations = [
        migrations.AddField(
            model_name='baseuser',
            name='bio',
            field=models.TextField(blank=True, max_length=300),
        ),
    ]
