# Generated by Django 6.0.3 on 2026-04-02 12:48

import django.core.validators
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('author', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Book',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('book_slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('pages', models.PositiveIntegerField(blank=True, validators=[django.core.validators.MinValueValidator(10)])),
                ('description', models.TextField(blank=True, max_length=300)),
                ('genre', models.CharField(choices=[('fantasy', 'Fantasy'), ('drama', 'Drama'), ('science', 'Science'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('young adult', 'Young adult')], default='romance')),
                ('year_of_publishing', models.PositiveIntegerField(blank=True)),
                ('book_cover', models.ImageField(blank=True, null=True, upload_to='books_covers/')),
                ('author', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='books', to='author.author')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_books', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
