# Generated by Django 6.0.3 on 2026-04-02 13:32

import Reading_Club.book.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='books_covers/', validators=[Reading_Club.book.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
