# Generated by Django 6.0.3 on 2026-04-07 12:50

import Reading_Club.book.validators
import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0002_alter_book_book_cover_alter_book_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='book_cover',
            field=models.ImageField(blank=True, null=True, upload_to='media/books_covers/', validators=[Reading_Club.book.validators.validate_file_size]),
        ),
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('Fantasy', 'Fantasy'), ('Drama', 'Drama'), ('Science', 'Science'), ('Romance', 'Romance'), ('Mystery', 'Mystery'), ('Young adult', 'Young adult')], default='Romance', max_length=30),
        ),
        migrations.AlterField(
            model_name='book',
            name='pages',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(10)]),
        ),
        migrations.AlterField(
            model_name='book',
            name='year_of_publishing',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
