# Generated by Django 6.0.3 on 2026-04-09 09:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0003_alter_book_book_cover_alter_book_genre_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='book',
            name='genre',
            field=models.CharField(choices=[('fantasy', 'Fantasy'), ('drama', 'Drama'), ('science', 'Science'), ('romance', 'Romance'), ('mystery', 'Mystery'), ('young adult', 'Young adult')], default='romance', max_length=30),
        ),
    ]
