# Generated by Django 6.0.3 on 2026-04-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='date_of_publication',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
