# Generated by Django 6.0.3 on 2026-04-17 09:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('review', '0003_alter_review_author'),
    ]

    operations = [
        migrations.AlterField(
            model_name='review',
            name='date_of_publication',
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
