# Generated by Django 6.0.3 on 2026-04-02 12:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('book', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Collection',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=120)),
                ('collection_slug', models.SlugField(blank=True, max_length=140, unique=True)),
                ('description', models.TextField()),
                ('cover', models.ImageField(blank=True, null=True, upload_to='collection_covers/')),
                ('books', models.ManyToManyField(related_name='collections', to='book.book')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='created_collection', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
