# Generated by Django 6.0.3 on 2026-04-18 06:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('collection', '0002_alter_collection_description'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collection',
            name='description',
            field=models.TextField(blank=True, max_length=500),
        ),
    ]
